export const SAVE_CREDENTIAL_SUBJECT = 'SAVE_CREDENTIAL_SUBJECT';
export const CHANGE_INPUT_CREDENTIAL_SUBJECT = 'CHANGE_INPUT_CREDENTIAL_SUBJECT';
export const CHANGE_INPUT_SUBJECT_PROFILE = 'CHANGE_INPUT_SUBJECT_PROFILE';
export const SAVE_SUBJECT_PROFILE = 'SAVE_SUBJECT_PROFILE';
export const SAVE_SUBJECT_PROFILE_DONE = 'SAVE_SUBJECT_PROFILE_DONE';
export const FETCH_SUBJECT_PROFILE = 'FETCH_SUBJECT_PROFILE';
export const FETCH_SUBJECT_PROFILE_DONE = 'FETCH_SUBJECT_PROFILE_DONE';

export const SAVE_CREDENTIAL = 'SAVE_CREDENTIAL';
export const CHANGE_INPUT_CREDENTIAL = 'CHANGE_INPUT_CREDENTIAL';
export const FETCH_CREDENTIAL_PROV_LIST = 'FETCH_CREDENTIAL_PROV_LIST';
export const FETCH_CREDENTIAL_PROV_LIST_WITH_CRED = 'FETCH_CREDENTIAL_PROV_LIST_WITH_CRED';
export const FETCH_CREDENTIAL_PROV_LIST_DONE = 'FETCH_CREDENTIAL_PROV_LIST_DONE';
export const FETCH_CREDENTIAL = 'FETCH_CREDENTIAL';
export const FETCH_CREDENTIAL_DONE = 'FETCH_CREDENTIAL_DONE';
export const CREATE_LINK = 'CREATE_LINK';
export const LINK_DETAILS_FETCH = 'LINK_DETAILS_FETCH';
export const LINK_DETAILS_FETCH_DONE = 'LINK_DETAILS_FETCH_DONE';

export const AUTH_SUCCESSFUL = 'AUTH_SUCCESSFUL';
export const AUTH_SUCCESSFUL_DONE = 'AUTH_SUCCESSFUL_DONE';
export const ACCOUNT_TYPE_DONE = 'ACCOUNT_TYPE_DONE';
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_REQUEST_DONE = 'LOGOUT_REQUEST_DONE';
